- name: Render JCL template
  ansible.builtin.template:
    src: "{{ source_jcl }}"
    dest: "{{ playbook_dir }}/rendered_jcl.txt"
  delegate_to: localhost

- name: Remove JCL member
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ delete_member }}"
    state: absent
    type: member

- name: Copy rendered JCL to z/OS
  ibm.ibm_zos_core.zos_copy:
    src: "{{ playbook_dir }}/rendered_jcl.txt"
    dest: "{{ submit_member }}"
    encoding:
      from: UTF-8
      to: IBM-1047

- name: Submit JCL
  ibm.ibm_zos_core.zos_job_submit:
    src: "{{ submit_member }}"
    location: DATA_SET
    wait_time_s: 10
  register: job_output

- name: Show job ID
  ansible.builtin.debug:
    msg: "{{ job_output.jobs[0].job_id }}"

