---
- name: Gather z/OS facts
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Gather z/OS facts
      ibm.ibm_zos_core.zos_gather_facts:
        gather_subset:
          - ipl
          - sys
      register: sytem_info
   
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: sytem_info
