---
- name: Create and verify KSDS
  hosts: zos
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:

    - name: Delete a data set if it exists
      ibm.ibm_zos_core.zos_data_set:
        name: This.is.my.test.ksds
        state: absent

    - name: Create a KSDS data set if it does not exist
      ibm.ibm_zos_core.zos_data_set:
        name: This.is.my.test.ksds
        type: ksds
        state: present
        record_length: 80
        key_length: 4
        key_offset: 0

    - name: Load records into the KSDS
      ibm.ibm_zos_core.zos_copy:
        content: |
          0001TEST RECORD 1
          0002TEST RECORD 2
        dest: This.is.my.test.ksds

    - name: Fetch records from the KSDS
      ibm.ibm_zos_core.zos_fetch:
        src: This.is.my.test.ksds
        dest: "{{ playbook_dir }}/KSDS_records.txt"
        flat: true

    - name: Read the fetched KSDS
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/KSDS_records.txt"
      delegate_to: localhost
      register: ksds_contents

    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ ksds_contents['content'] | b64decode }}"