---
- name: Submit JCL
  hosts: zos
  gather_facts: false

  collections:
    - ibm.ibm_zos_core

  environment: "{{ environment_vars }}"

  tasks:

    - name: Submit a PDS job
      zos_job_submit:
        src: "please.dont.make.me.share.my.screen(HELLO)"
        location: DATA_SET
        wait_time_s: 10
      register: job_output

    - name: Display echo output
      ansible.builtin.debug:
        msg: "{{ job_output.jobs[0].ddnames | selectattr('ddname', 'equalto', 'STDOUT') | map(attribute='content') | list }}"