---
- name: Create and load KSDS
  hosts: zos
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  vars:
    vsam_name: GAMA10.VSAM.KSDS

  tasks:

    - name: Delete KSDS if it exists
      zos_data_set:
        name: "{{ vsam_name }}"
        state: absent

    - name: Delete input sequential data set if it exists
      zos_data_set:
        name: "{{ vsam_name }}.INPUT"
        state: absent

    - name: Create KSDS
      zos_data_set:
        name: "{{ vsam_name }}"
        type: ksds
        state: present
        record_format: fb
        record_length: 80
        key_length: 4
        key_offset: 0
        space_primary: 2
        space_secondary: 1
        space_type: cyl
      register: create_ksds_result

    - name: Show KSDS creation result
      debug:
        var: create_ksds_result

    - name: Create input sequential data set
      zos_data_set:
        name: "{{ vsam_name }}.INPUT"
        type: seq
        state: present
        record_format: fb
        record_length: 80
        space_primary: 1
        space_secondary: 1
        space_type: cyl
      register: create_input_result

    - name: Show input data set creation result
      debug:
        var: create_input_result

    - name: Copy records to input sequential data set
      zos_copy:
        src: "{{ playbook_dir }}/KSDS_records.txt"
        dest: "{{ vsam_name }}.INPUT"
        encoding:
          from: UTF-8
          to: IBM-1047
      register: populate_input_result

    - name: Show populate input result
      debug:
        var: populate_input_result

    - name: Load records into KSDS using IDCAMS REPRO
      zos_mvs_raw:
        program_name: IDCAMS
        auth: true
        dds:
          - dd_data_set:
              dd_name: INPUT
              data_set_name: "{{ vsam_name }}.INPUT"
              disposition: shr

          - dd_data_set:
              dd_name: OUTPUT
              data_set_name: "{{ vsam_name }}"
              disposition: shr

          - dd_input:
              dd_name: SYSIN
              content: |
                REPRO -
                  INFILE(INPUT) -
                  OUTFILE(OUTPUT)

          - dd_output:
              dd_name: SYSPRINT
              return_content:
                type: text
      register: load_ksds_result

    - name: Show load result
      debug:
        var: load_ksds_result