---
- name: Submit JCL
  hosts: zos
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  vars:
    job_name: "HELOWRLD"
    bye: "Hello kendrick!"

  tasks:

    - name: Render JCL template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/JCL/Hello_jcl_jin.txt"
        dest: "{{ playbook_dir }}/sample_job.j2"
      delegate_to: localhost

    - name: Remove a member from an existing PDS
      zos_data_set:
        name: "please.dont.make.me.share.my.screen(HELLO2)"
        state: absent
        type: member

    - name: Copy rendered JCL to z/OS
      zos_copy:
        src: "{{ playbook_dir }}/Hello_JCL.txt"
        dest: "please.dont.make.me.share.my.screen(HELLO2)"
        encoding:
          from: UTF-8
          to: IBM-1047

    - name: Submit JCL
      zos_job_submit:
        src: "please.dont.make.me.share.my.screen(HELLO2)"
        location: DATA_SET
        wait_time_s: 30
      register: job_output

    - name: Show job ID
      ansible.builtin.debug:
        msg: "{{ job_output.jobs[0].job_id }}"