---
- name: Create and verify KSDS
  hosts: zos
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:

    - name: Delete a data set if it exists
      zos_data_set:
        name: This.is.my.test.ksds
        state: absent

    - name: Create a KSDS data set if it does not exist
      zos_data_set:
        name: This.is.my.test.ksds
        type: ksds
        state: present
        record_length: 80
        key_length: 4
        key_offset: 0

    - name: Check KSDS records file
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/KSDS_records.txt"
      delegate_to: localhost
      register: ksds_file

    - name: Show KSDS records file
      ansible.builtin.debug:
        var: ksds_file

    - name: Load records into the KSDS
      zos_encode:
        src: "{{ playbook_dir }}/KSDS_records.txt"
        dest: This.is.my.test.ksds
        encoding:
          from: UTF-8
          to: IBM-1047

    - name: Fetch records from the KSDS
      zos_fetch:
        src: This.is.my.test.ksds
        dest: "{{ playbook_dir }}/KSDS_records.txt"
        flat: true

    - name: Read the fetched KSDS
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/KSDS_records.txt"
      delegate_to: localhost
      register: ksds_contents

    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ ksds_contents['content'] | b64decode }}"