---
- name: z/OS System Dashboard
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:

    - name: Query all active jobs
      ibm.ibm_zos_core.zos_job_query:
      register: active_jobs

    - name: Show job query results
      ansible.builtin.debug:
        var: active_jobs.jobs

    - name: Keep only started tasks
      ansible.builtin.set_fact:
        started_tasks: >-
          {{
            active_jobs.jobs
            | selectattr('job_class', 'defined')
            | selectattr('job_class', 'equalto', 'STC')
            | list
          }}

    - name: Show started tasks
      ansible.builtin.debug:
        var: started_tasks